# Generated by Django 2.2.6 on 2019-10-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('key', models.CharField(max_length=200)),
                ('train_or_not', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorical_columns', models.CharField(max_length=10000)),
                ('numerical_columns', models.CharField(max_length=10000)),
                ('id_column', models.CharField(max_length=1000)),
                ('label_column', models.CharField(max_length=1000)),
                ('key', models.CharField(max_length=200)),
            ],
        ),
    ]
