# Generated by Django 2.2.6 on 2019-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='datasetdescription',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
