# Generated by Django 2.2.6 on 2019-10-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_importantfeature_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
